
export const COMMON_DOMAINS = [
  'gmail.com',
  'yahoo.com',
  'outlook.com',
  'hotmail.com',
  'protonmail.com',
  'proton.me',
  'icloud.com',
];

export const EMAIL_SVG = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij4KPHBhdGggZmlsbD0iI2QxYzRlOSIgZD0iTTQyLjQ0OSw5LjI2NEwyNi4zNTUsMjIuMDg4Yy0xLjQwMSwxLjExNy0zLjQwNCwxLjExMi00LjgtMC4wMUw1LjUzNSw5LjE5OElDNC45MDksOC43MjEsNCw5LjE2MSw0LDkuOTQxdjUuNjAzdjE5LjczMmMwLDIuMDc2LDEuNzA2LDMuNzU4LDMuODEsMy43NThINDAuMTljMi4xMDQsMCwzLjgxLTEuNjgzLDMuODEtMy43NThWOS45OTUJQzQ0LDkuMjA1LDQzLjA3Miw4Ljc2Nyw0Mi40NDksOS4yNjR6Ij48L3BhdGg+PHBhdGggZmlsbD0iIzdjNGRmZiIgZD0iTTM1LjQyOSwxNC44NThsLTEzLjc5LDEwLjk4OGMtMS40LDEuMTE1LTMuMzk5LDEuMTEyLTQuNzk2LTAuMDA3TDQsMTUuNTQ1djE5LjczMgljMCwyLjA3NiwxLjcwNiwzLjc1OCwzLjgxLDMuNzU4aDI3LjYxOVYxNC44NTh6Ij48L3BhdGg+Cjwvc3ZnPg==';

export const GMAIL_SVG = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij4KPHBhdGggZmlsbD0iIzRjYWY1MCIgZD0iTTQ1LDE2LjJsLTUsMi43NWwtNSw0Ljc1TDM1LDQwaDdjMS42NTcsMCwzLTEuMzQzLDMtM1YxNi4yeiI+PC9wYXRoPjxwYXRoIGZpbGw9IiMxZTg4ZTUiIGQ9Ik0zLDE2LjJsMy42MTQsMS43MUwxMywyMy43VjQwSDZjLTEuNjU3LDAtMy0xLjM0My0zLTNWMTYuMnoiPjwvcGF0aD4KPHBvbHlnb24gZmlsbD0iI2U1MzkzNSIgcG9pbnRzPSIzNSwxMS4yIDI0LDE5LjQ1IDEzLDExLjIgMTIsMTcgMTMsMjMuNyAyNCwzMS45NSAzNSwyMy43IDM2LDE3Ij48L3BvbHlnb24+PHBhdGggZmlsbD0iI2M2MjgyOCIgZD0iTTMsMTIuMjk4VjE2LjJsMTAsNy41VjExLjJMOS44NzYsOC44NTlDOS4xMzIsOC4zMDEsOC4yMjgsOCw3LjI5OCw4aDBDNC45MjQsOCwzLDkuOTI0LDMsMTIuMjk4eiI+PC9wYXRoPjxwYXRoIGZpbGw9IiNmYmMwMmQiIGQ9Ik00NSwxMi4yOThWMTYuMmwtMTAsNy42VjExLjJsMy4xMjQtMi4zNDFDMzguODY4LDguMzAxLDM5Ljc3Miw4LDQwLjcwMiw4aDAgQzQzLjA3Niw4LDQ1LDkuOTI0LDQ1LDEyLjI5OHoiPjwvcGF0aD4KPC9zdmc+';

export const FAVICON_OVERRIDES: Record<string, string> = {
  'gmail.com': GMAIL_SVG,
  'yahoo.com': 'https://s.yimg.com/rz/l/favicon.ico',
  'outlook.com': 'https://outlook.com/favicon.ico',
  'hotmail.com': 'https://outlook.com/favicon.ico',
  'icloud.com': 'https://www.icloud.com/favicon.ico',
  'protonmail.com': EMAIL_SVG,
  'proton.me': EMAIL_SVG,
};
